Feature
maryfelmendoza/enumerables pull request #2
Opened 2020-01-16 17:53 UTC by maryfelmendoza

2020-01-16 20:47 UTC, mcrd25 requested changes
# Changes Required 🔍 👀 

Hi @maryfelmendoza, 👋 

You have done a really good job so far, just a couple more changes to make to get this to 💯 !

### Required Changes
*Summary of changes needed that would be expounded upon in the review comments:*
- Address missing functionality of `my_each`
- Address missing functionality of `my_each_with_index`
- Address missing functionality of `my_select`
- Address missing functionality of `my_all?`
- Address missing functionality of `my_none?`
- Address missing functionality of `my_any?`
- Address missing functionality for `my_map`
- Address issues with `my_inject`

I hope my review helps you address missing pieces of your project and that you are closer to getting the 👍 for the next review. 😄 



***Please makes changes and submit another review request.
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2020-01-16 20:47 UTC, mcrd25 commented on code.rb
> +  def my_each
This method should return an Enumerator when no block is given

This can be done in the following manner using `to_enum :my_each` and I'd sure you can figure out the rest. 😄

2020-01-16 20:47 UTC, mcrd25 commented on code.rb
> +  def my_each_with_index
Just as with `my_each`, `my_each_with_index` should return an Enumerator when a block is not given.
In the same manner, using `to_enum :name_of_method` -> This can be used for each that requires a return of `Enumerator`

2020-01-16 20:47 UTC, mcrd25 commented on code.rb
> +  def my_select
This method should return an Enumerator when no block is given.

2020-01-16 20:47 UTC, mcrd25 commented on code.rb
> +        all_true = false unless x == val
Best to use `===` here

2020-01-16 20:47 UTC, mcrd25 commented on code.rb
> +  def my_all?(val = nil)
This method looks fine, but it should also take into consideration when a class or RegEx is passed as an argument for `val`.

My comment below would be able to cover those cases.
See [enumerable docs](https://ruby-doc.org/core-2.7.0/Enumerable.html) for info on the original `all?` method

2020-01-16 20:47 UTC, mcrd25 commented on code.rb
> +  def my_any?(val = nil)
Same issue with `my_all?` applies to this `my_any?` method

2020-01-16 20:47 UTC, mcrd25 commented on code.rb
> +  def my_none?(val = nil)
Similar issues as with the previous two methods.
Consider Classes and Regular Expressions

2020-01-16 20:47 UTC, mcrd25 commented on code.rb
> +  def my_map(my_proc = nil)
Should return an Enumerator when no block is given

2020-01-16 20:47 UTC, mcrd25 commented on code.rb
> +  def my_inject(init = nil, proc = nil)
Your `my_inject` does not quite work as should.
Please see a screenshot of failed tests below:
![Screen Shot 2020-01-16 at 4 41 49 PM](https://user-images.githubusercontent.com/31193823/72561489-b82a3f80-387f-11ea-934e-b14cf70559ff.png)

You can read more about the original `inject` method in this [documentation](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-inject)

2020-01-22 20:36 UTC, maryfelmendoza commented
I fixed some of the methods. I would like to know if im in the right path of what you requested me to continue with the other ones or if I have any erros

2020-01-22 22:40 UTC, Anna-Myzukina commented
### Pull Request under the review by Anna Muzykina (TSE)

2020-01-22 23:00 UTC, Anna-Myzukina commented
## Hi @maryfelmendoza  ! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 

# Status: [changes required]


* Kindly recommended following advice of previous TSE Maya

#### Next methods still working not correct:
* my_any?

* my_none?

* my_map

* my_inject


### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding *

2020-01-22 23:00 UTC, Anna-Myzukina requested changes
Few methods still need changes

2020-01-22 23:31 UTC, maryfelmendoza commented
I already fixed the other methods requiered

2020-01-23 00:17 UTC, suretrust requested changes
Hi @maryfelmendoza, 👋 

### Great job thus far. 🙌 Just a few test cases to go. 💯 

- [ ] Please see my comment on your code.

**Kindly submit for another code review once these issues have been fixed.**  _Happy coding!_ 🎉

2020-01-23 00:17 UTC, suretrust commented on code.rb
> +end
* [ ] `my_inject` method should be identical and returns the same thing as ruby's [`inject`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-inject). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_inject.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

- [ ]  Enumerables `my_inject` combines all elements of enum by applying a binary operation, specified by a block

```ruby
[1,2,3,4,5,6].my_inject(&:+) != [1,2,3,4,5,6].inject(&:+)
```

- [ ]  Enumerables `my_inject` when a symbol is specified combines each element of the collection by applying the symbol as a named method

```ruby
[1,2,3,4,5,6].my_inject(:+) == [1,2,3,4,5,6].inject(:+)
```

2020-01-23 01:09 UTC, maryfelmendoza commented
Fixed my_inject

2020-01-23 10:46 UTC, stratospherique requested changes
### Great progress :clap: :clap: Almost there :wink:  However, some methods need further refactoring in order to get approval for the project. Check :arrow_down: 

- **[REQUIRED]** Check the code comments below, they should help you refactor your methods :gear: 

### That's it :relieved: When finished, kindly resubmit another code review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

2020-01-23 10:46 UTC, stratospherique commented on code.rb
> +  end
* [ ] should have working `my_map` identical and returns the same thing as ruby's [`map`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-map). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_map.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

* [ ] my_map returns a new array with the results of running block once for every element in enum.
  ```ruby
    array = [1,2,5,4,7]
    block = proc { |num| num < 5 }
    p array.my_map?(&block) == array.map?(&block) # false
  ```

2020-01-23 10:46 UTC, stratospherique commented on code.rb
> +end
* [ ] should have working `my_inject` identical and returns the same thing as ruby's [`inject`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-inject). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_inject.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
* [ ] my_inject combines all elements of enum by applying a binary operation, specified by a block
  ```ruby
    range = Range.new(5, 50)
    p range.my_inject(4) { |prod, n| prod * n } # returns this error
    # NoMethodError:
       undefined method `length' for 5..50:Range
     # ./code.rb:5:in `my_each'
     # ./code.rb:166:in `my_inject'
  ```
* [ ] my_inject when a symbol is specified combines each element of the collection by applying the symbol as a named method
  ```ruby
    range = Range.new(5, 50)
    p range.my_inject(2, :*) # returns this error
    # NoMethodError:
       undefined method `length' for 5..50:Range
     # ./code.rb:5:in `my_each'
     # ./code.rb:156:in `my_inject'
  ```

2020-02-06 19:53 UTC, Forison approved these changes
### Status:Approved💚
# Good job on implementing the changes suggested💪 in the previous reviews. 
Your project is approved go ahead and merge. 
#### ** [ optional ]**
- [x] Pull Request has meaningful title and a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
#### Happy coding💻
#### Addo Forison

2020-02-06 20:04 UTC, merged